learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
]

learning_logs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有主题
    path('topics/', views.topics, name='topics'),
    # 显示特定主题的详细页面
    path('topics/<topic_id>/', views.topic, name='topic'),
    # 其他用户添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新记录的页面
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),
    # 用于编辑记录的页面
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views


urlpatterns = [
    # 登陆页面
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login'),
    # 注销页面
    path('logout/', views.logout_view, name='logout'),
    # 注册页面
    path('register', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    # 用户学习的主题
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # Python和Django在要将模型实例展示为纯文本对象时调用。
    def __str__(self):
        # 返回模型的字符串表示
        return self.text


class Entry(models.Model):
    # 学到有关某个主题的具体知识
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) # ManyToManyField OneToOneField
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        # 模型的元数据即“所有不是字段的东西”，比如排序选项（ordering），数据库表名（db_table），或是阅读友好的单复数名（verbose_name和verbose_name_plural）。
        verbose_name_plural = 'entries'

    def __str__(self):
        # 返回模型的字符串表示
        return self.text[:50] + "..."


users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from . models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
# 导入django自带模块
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# 导入自己编写的模块
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    # 学习笔记的主页
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    # 显示某个主题及其所有条目
    topic = get_object_or_404(Topic, id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    # 添加新主题
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # 对POST提交数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    # 在特定的主题中添加新条目
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据：创建一个空表单
        form = EntryForm()
    else:
        # 对POST提交数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic #???????
            new_entry.save() #?????
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    # 编辑现有记录
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 保护页面不被其他人修改
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求，使用当前记录填充表单
        form = EntryForm(instance=entry)
    else:
        # 对POST提交数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'form': form, 'topic': topic}
    return render(request, 'learning_logs/edit_entry.html', context)



users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def logout_view(request):
    # 注销用户
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    # 注册账户
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 对POST提交表单进行处理
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 用户自动登录，并回到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)



learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load i18n%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- 头部不包含内容 -->
        <meta charset="utf-8">
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>头发の笔记</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        <!-- 静态导航 -->
        <nav class='navbar navbar-default navbar-static-top bg-pink'>
            <div class='container'>
                <div class='navbar-header'>
                    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记</a>
                </div>

                <div class="navbar-collapse collapse" id="navbar">
                    <ul class='nav navbar-nav'>
                        <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
                    </ul>
                    <ul class='nav navbar-nav navbar-right'>
                        {% if user.is_authenticated %}
                            <li><a>你好，{{ user.username }}!</a></li>
                            <li><a href="{% url 'users:logout' %}">注销</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">注册</a></li>
                            <li><a href="{% url 'users:login' %}">登陆</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            <div class='container'>
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h3><a herf="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock header %}
{% load bootstrap3 %}

{% block content %}
    <div class='container'>
        <h6>.</h6>
        <h4>编辑此条记录</h4>
        <h6>.</h6>

        <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <h6>.</h6>
            {% buttons %}
                <button class='btn btn-primary' name='submit'>保存更改</button>
            {% endbuttons %}
        </form>

    </div>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <div class='jumbotron'>
        <h3>欢迎来到头发の日志！</h3>
        <h3>学习日志帮助你记录学习历程，你可以新建任何你想学的主题！</h3>
        <h3>注册账号开始你的学习之旅吧！</h3>
    </div>
{% endblock header %}

{% block content %}

    <div class="container">
        <div class="form-group">
            <div class="col-md-10">
                <h3><a href="{% url 'users:register' %}">注册账户</a></h3>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h3>当你学习某个新的主题时，可以新建学习记录来总结你学到知识！</h3>
                <h3>让我们共同进步吧！</h3>

            </div>
        </div>


    </div>

{% endblock content %}


learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h3><a herf="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock header %}

{% block content %}
    <div class='container'>
        <h6>.</h6>
        <h4>添加一条记录</h4>
        <h6>.</h6>
        <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <h6>.</h6>
            {% buttons %}
                <button class='btn btn-primary' name='submit'>新建记录</button>
            {% endbuttons %}
        </form>
    </div>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h4></h4>
{% endblock header %}

{% block content %}

    <form class='container' action="{% url 'learning_logs:new_topic' %}" method='post'>

        <div class="col-md-8">
            <h4>新增一个主题</h4>
            <h6>.</h6>
            {% csrf_token %}
            {% bootstrap_form form %}
            <h6>.</h6>
            {% buttons %}
                <button class='btn btn-primary' name='submit'>新建主题</button>
            {% endbuttons %}
        </div>

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

    <div class='container'>
        
        <h4>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">添加记录</a>
        </h4>

    {% for entry in entries %}

        <div class='panel panel-default'>
            <div class='panel-heading'>
                <h4>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑记录</a>
                    </small>
                </h4>
            </div>
            <div class='panel-body'>
                {{ entry.text|linebreaks }}
            </div>
        </div>

        {% empty %}
            <h6>.</h6>
            <h4>请开始你{{ topic }}的第一条记录...</h4>
        {% endfor %}
    </div>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>主题</h2>
{% endblock header %}

{% block content %}
    <div class='container'>
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>目前还没有主题...</li>
        {% endfor %}
    </ul>
    <h6>.</h6>
    <h3>
        <a href="{% url 'learning_logs:new_topic' %}">添加主题</a>
    </h3>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h4>请登陆你的账号！</h4>
{% endblock header %}

{% block content %}

    <form class='container' action="{% url 'users:login' %}" method='post'>

        <div class="col-md-6">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name='submit' class='btn btn-primary'>登陆</button>
            {% endbuttons %}
        </div>

        <input type='hidden' name='next' value="{% url 'learning_logs:index' %}"/>
    </form>
    
{% endblock content %}

users/templates/users/logout.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    {% if form.errors %}
    <p>用户名和密码不匹配，请再试一次！</p>
    {% endif %}

    <form action="{% url 'users:logout' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    
    <button name='submit'>退出登陆</button>
    <input type='hidden' name='next' value="{% url 'learning_logs:index' %}"/>
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <form action="{% url 'users:register' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}

    <button name='submit'>注册</button>
    <input type='hidden' name='next' value="{% url 'learning_logs:index' %}"/>
    </form>

{% endblock content %}